<?php

/**
 * @file
 * INPI Commerce Product Types.
 */

/**
 * Implements hook_menu().
 */
 // echo strlen('123123123213123213213213123213123123123123123213123213213123213213213213213213213123213212312312321312321321321312321312312312312312321312321321312321321321321321321321312321321312321321312321123123123213123213213213123213123123123123123211312321321312321');
function inpicom_pt_demande_de_devis_menu() {
	$menu['custom_test'] = array(
		'title'            => 'Demande de devis',
		'description'      => 'Creates an ajax multistep form',
		'page callback'    => 'drupal_get_form',
		'page arguments'   => array('inpicom_pt_demande_de_devis_multistep_form'),
		'access callback'  => TRUE,
	);
	return $menu;
}
//
function inpicom_pt_demande_de_devis_load($product_id) {
 if (empty($product_id)) {
   return FALSE;
 }

 $products = commerce_product_load_multiple(array($product_id), array());
 return $products ? reset($products) : FALSE;
}
function inpicom_pt_demande_de_devis_multistep_form($form, &$form_state) {
  $form_state['step'] = isset($form_state['step']) ? $form_state['step'] : 1;
  $form['#prefix']    = '<div id="inpicom_pt_demande_de_devis_multistep_form">';
  $form['#suffix']    = '</div>';
  switch ($form_state['step']) {
    // Step 1
    case 1:
      inpicom_pt_demande_de_devis_multistep_form_step_one($form, $form_state);
      break;
    case 2:
      inpicom_pt_demande_de_devis_multistep_form_step_tow($form, $form_state);
      break;
    // Step 2
    case 3:
      inpicom_pt_demande_de_devis_multistep_form_step_three($form, $form_state);
      break;
    // Step 3
    case 4:
      inpicom_pt_demande_de_devis_multistep_form_step_four($form, $form_state);
      break;
  }
  inpicom_pt_demande_de_devis_multistep_form_render_button($form, $form_state);
  return $form;
}

function inpicom_pt_demande_de_devis_multistep_form_render_button(&$form, $form_state) {
  $form['buttons'] = array(
    '#type' => 'container',
  );
  if ($form_state['step'] !== 1) {
    $form['buttons']['back'] = array(
      '#type'   => 'submit',
      '#value'  => t('Back'),
      '#limit_validation_errors' => array(),
      '#submit' => array('inpicom_pt_demande_de_devis_multistep_form_back_submit'),
      '#ajax'   => array(
        'wrapper'  => 'inpicom_pt_demande_de_devis_multistep_form',
        'callback' => 'inpicom_pt_demande_de_devis_multistep_form_ajax_callback',
      ),
    );
  }
  if ($form_state['step'] !== 4) {
    $form['buttons']['forward'] = array(
      '#type'  => 'submit',
      '#value' => t('Next'),
      '#ajax'  => array(
        'wrapper' => 'inpicom_pt_demande_de_devis_multistep_form',
        'callback' => 'inpicom_pt_demande_de_devis_multistep_form_ajax_callback',
      ),
    );
  }
  else {
    $form['buttons']['submit'] = array(
      '#type'  => 'submit',
      '#value' => t('Submit'),
      '#ajax'  => array(
        'wrapper' => 'inpicom_pt_demande_de_devis_multistep_form',
        'callback' => 'inpicom_pt_demande_de_devis_multistep_form_ajax_callback',
      ),
    );
  }
  return $form;
}

function inpicom_pt_demande_de_devis_multistep_form_step_one(&$form, &$form_state) {
  return $form;
}

function inpicom_pt_demande_de_devis_multistep_form_step_tow(&$form, &$form_state) {
  $form['votre_demande'] = array(
    '#type'  => 'textarea',
    '#title' => t('Votre demande'),
    '#required'      => TRUE,
    '#placeholder'   => t('Ecrivez ici votre demande'),
    '#default_value' => inpicom_pt_demande_de_devis_get_votre_demande_value($form_state),
  );
  $form['file_upload'] = array(
    //'#name'  => 'files[' . implode('_', $element['#parents']) . ']',
    '#type'  => 'file',
    '#title' => t('Ajouter un fichier'),
    '#title_display'  => 'invisible',
    '#size'  => 22,
    '#theme_wrappers' => array(),
    '#weight'=> -10,
  );
}

function inpicom_pt_demande_de_devis_multistep_form_step_three(&$form, &$form_state) {
  $active = array(0 => t('Ma$formdame'), 1 => t('Monsieur'));
  $form['civilite'] = array(
    '#type'  => 'radios',
    '#title' => t('Civilite'),
    '#required'      => TRUE,
    '#default_value' => inpicom_pt_demande_de_devis_get_civilite_value($form_state),
    '#options'       => $active,
  );
  $form['nom'] = array(
    '#type' => 'textfield',
    '#title' => t('Nom'),
    '#required' => TRUE,
    '#default_value' => inpicom_pt_demande_de_devis_get_nom_value($form_state),
  );
  $form['prenom'] = array(
    '#type'  => 'textfield',
    '#title' => t('Prenom'),
    '#required'      => TRUE,
    '#default_value' => inpicom_pt_demande_de_devis_get_prenom_value($form_state),
  );
  $form['mel'] = array(
    '#type' => 'textfield',
    '#title' => t('Mel'),
    '#required' => TRUE,
    '#default_value' => inpicom_pt_demande_de_devis_get_mel_value($form_state),
  );
  $active = array(0 => t('Personne physique'), 1 => t('Personne morale'), 2 => t('Mandataire'));
  $form['vous_etes'] = array(
    '#type' => 'radios',
    '#title' => t('Vous êtes'),
    '#default_value' => inpicom_pt_demande_de_devis_get_vous_etes_value($form_state),
    '#options' => $active,
  );
  $form['profession'] = array(
    '#type' => 'textfield',
    '#title' => t('Profession'),
    '#maxlength' => 1024,
    '#default_value' => inpicom_pt_demande_de_devis_get_profession_value($form_state),
  );
  $form['role'] = array(
    '#type' => 'select',
    '#title' => t('Rôle'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => inpicom_pt_demande_de_devis_get_role_value($form_state),
  );
  $form['pays'] = array(
    '#type' => 'select',
    '#title' => t('Pays'),
    '#options' => array(
''=> t('- Sélectionner -'),
'AF'=> t('Afghanistan'),
'ZA'=> t('Afrique du Sud'),
'AL'=> t('Albanie'),
'DZ'=> t('Algérie'),
'DE'=> t('Allemagne'),
'AD'=> t('Andorre'),
'AO'=> t('Angola'),
'AI'=> t('Anguilla'),
'AQ'=> t('Antarctique'),
'AG'=> t('Antigua-et-Barbuda'),
'AN'=> t('Antilles néerlandaises'),
'SA'=> t('Arabie Saoudite'),
'AR'=> t('Argentine'),
'AM'=> t('Arménie'),
'AW'=> t('Aruba'),
'AU'=> t('Australie'),
'AT'=> t('Autriche'),
'AZ'=> t('Azerbaïdjan'),
'BS'=> t('Bahamas'),
'BH'=> t('Bahreïn'),
'BD'=> t('Bangladesh'),
'BB'=> t('Barbade'),
'BE'=> t('Belgique'),
'BZ'=> t('Belize'),
'BM'=> t('Bermudes'),
'BT'=> t('Bhoutan'),
'MM'=> t('Birmanie'),
'BY'=> t('Biélorussie'),
'BO'=> t('Bolivie'),
'BA'=> t('Bosnie-Herzégovine'),
'BW'=> t('Botswana'),
'BN'=> t('Brunei'),
'BR'=> t('Brésil'),
'BG'=> t('Bulgarie'),
'BF'=> t('Burkina Faso'),
'BI'=> t('Burundi'),
'BJ'=> t('Bénin'),
'KH'=> t('Cambodge'),
'CM'=> t('Cameroun'),
'CA'=> t('Canada'),
'CV'=> t('Cap-Vert'),
'CL'=> t('Chili'),
'CN'=> t('Chine'),
'CY'=> t('Chypre'),
'CO'=> t('Colombie'),
'KM'=> t('Comores'),
'CG'=> t('Congo (Brazzaville)'),
'CD'=> t('Congo (Kinshasa)'),
'KP'=> t('Corée du Nord'),
'KR'=> t('Corée du Sud'),
'CR'=> t('Costa Rica'),
'HR'=> t('Croatie'),
'CU'=> t('Cuba'),
'CW'=> t('Curaçao'),
'CI'=> t('Côte d’Ivoire'),
'DK'=> t('Danemark'),
'DJ'=> t('Djibouti'),
'DM'=> t('Dominique'),
'ES'=> t('Espagne'),
'EE'=> t('Estonie'),
'FJ'=> t('Fidji'),
'FI'=> t('Finlande'),
'FR'=> t('France'),
'GA'=> t('Gabon'),
'GM'=> t('Gambie'),
'GH'=> t('Ghana'),
'GI'=> t('Gibraltar'),
'GD'=> t('Grenade'),
'GL'=> t('Groenland'),
'GR'=> t('Grèce'),
'GP'=> t('Guadeloupe'),
'GU'=> t('Guam'),
'GT'=> t('Guatemala'),
'GG'=> t('Guernesey'),
'GN'=> t('Guinée'),
'GW'=> t('Guinée-Bissau'),
'GQ'=> t('Guinée équatoriale'),
'GY'=> t('Guyana'),
'GF'=> t('Guyane française'),
'GE'=> t('Géorgie'),
'GS'=> t('Géorgie du Sud et les Îles Sandwich du Sud'),
'HT'=> t('Haïti'),
'HN'=> t('Honduras'),
'HK'=> t('Hong Kong R.A.S., Chine'),
'HU'=> t('Hongrie'),
'IN'=> t('Inde'),
'ID'=> t('Indonésie'),
'IQ'=> t('Irak'),
'IR'=> t('Iran'),
'IE'=> t('Irlande'),
'IS'=> t('Islande'),
'IL'=> t('Israël'),
'IT'=> t('Italie'),
'JM'=> t('Jamaïque'),
'JP'=> t('Japon'),
'JE'=> t('Jersey'),
'JO'=> t('Jordanie'),
'KZ'=> t('Kazakhstan'),
'KE'=> t('Kenya'),
'KG'=> t('Kirghizistan'),
'KI'=> t('Kiribati'),
'KW'=> t('Koweït'),
'LA'=> t('Laos'),
'LS'=> t('Lesotho'),
'LV'=> t('Lettonie'),
'LB'=> t('Liban'),
'LR'=> t('Libéria'),
'LI'=> t('Liechtenstein'),
'LT'=> t('Lituanie'),
'LU'=> t('Luxembourg'),
'LY'=> t('Lybie'),
'MO'=> t('Macao R.A.S., Chine'),
'MK'=> t('Macédoine'),
'MG'=> t('Madagascar'),
'MY'=> t('Malaisie'),
'MW'=> t('Malawi'),
'MV'=> t('Maldives'),
'ML'=> t('Mali'),
'MT'=> t('Malte'),
'MA'=> t('Maroc'),
'MQ'=> t('Martinique'),
'MU'=> t('Maurice'),
'MR'=> t('Mauritanie'),
'YT'=> t('Mayotte'),
'MX'=> t('Mexique'),
'FM'=> t('Micronésie'),
'MD'=> t('Moldavie'),
'MC'=> t('Monaco'),
'MN'=> t('Mongolie'),
'MS'=> t('Montserrat'),
'ME'=> t('Monténégro'),
'MZ'=> t('Mozambique'),
'NA'=> t('Namibie'),
'NR'=> t('Nauru'),
'NI'=> t('Nicaragua'),
'NE'=> t('Niger'),
'NG'=> t('Nigeria'),
'NU'=> t('Niue'),
'NO'=> t('Norvège'),
'NC'=> t('Nouvelle-Calédonie'),
'NZ'=> t('Nouvelle-Zélande'),
'NP'=> t('Népal'),
'OM'=> t('Oman'),
'UG'=> t('Ouganda'),
'UZ'=> t('Ouzbékistan'),
'PK'=> t('Pakistan'),
'PW'=> t('Palaos'),
'PA'=> t('Panama'),
'PG'=> t('Papouasie-Nouvelle-Guinée'),
'PY'=> t('Paraguay'),
'NL'=> t('Pays-Bas'),
'BQ'=> t('Pays-Bas caribéens'),
'PH'=> t('Philippines'),
'PN'=> t('Pitcairn'),
'PL'=> t('Pologne'),
'PF'=> t('Polynésie française'),
'PR'=> t('Porto Rico'),
'PT'=> t('Portugal'),
'PE'=> t('Pérou'),
'QA'=> t('Qatar'),
'RO'=> t('Roumanie'),
'GB'=> t('Royaume-Uni'),
'RU'=> t('Russie'),
'RW'=> t('Rwanda'),
'CF'=> t('République centrafricaine'),
'DO'=> t('République dominicaine'),
'CZ'=> t('République tchèque'),
'RE'=> t('Réunion'),
'EH'=> t('Sahara occidental'),
'BL'=> t('Saint-Barthélemy'),
'KN'=> t('Saint-Christophe-et-Niévès'),
'SM'=> t('Saint-Marin'),
'SX'=> t('Saint-Martin'),
'MF'=> t('Saint-Martin (partie française)'),
'PM'=> t('Saint-Pierre-et-Miquelon'),
'VC'=> t('Saint-Vincent-et-les-Grenadines'),
'SH'=> t('Sainte-Hélène'),
'LC'=> t('Sainte-Lucie'),
'SV'=> t('Salvador'),
'WS'=> t('Samoa'),
'AS'=> t('Samoa américaines'),
'ST'=> t('Sao Tomé-et-Principe'),
'RS'=> t('Serbie'),
'SC'=> t('Seychelles'),
'SL'=> t('Sierra Leone'),
'SG'=> t('Singapour'),
'SK'=> t('Slovaquie'),
'SI'=> t('Slovénie'),
'SO'=> t('Somalie'),
'SD'=> t('Soudan'),
'SS'=> t('Soudan du Sud'),
'LK'=> t('Sri Lanka'),
'CH'=> t('Suisse'),
'SR'=> t('Suriname'),
'SE'=> t('Suède'),
'SJ'=> t('Svalbard et Île Jan Mayen'),
'SZ'=> t('Swaziland'),
'SY'=> t('Syrie'),
'SN'=> t('Sénégal'),
'TJ'=> t('Tadjikistan'),
'TZ'=> t('Tanzanie'),
'TW'=> t('Taïwan'),
'TD'=> t('Tchad'),
'TF'=> t('Terres australes françaises'),
'IO'=> t('Territoire britannique de locéan Indien'),
'PS'=> t('Territoire palestinien'),
'TH'=> t('Thaïlande'),
'TL'=> t('Timor oriental'),
'TG'=> t('Togo'),
'TK'=> t('Tokelau'),
'TO'=> t('Tonga'),
'TT'=> t('Trinité-et-Tobago'),
'TN'=> t('Tunisie'),
'TM'=> t('Turkménistan'),
'TR'=> t('Turquie'),
'TV'=> t('Tuvalu'),
'UA'=> t('Ukraine'),
'UY'=> t('Uruguay'),
'VU'=> t('Vanuatu'),
'VA'=> t('Vatican'),
'VE'=> t('Venezuela'),
'VN'=> t('Vietnam'),
'WF'=> t('Wallis et Futuna'),
'YE'=> t('Yémen'),
'ZM'=> t('Zambie'),
'ZW'=> t('Zimbabwe'),
'EG'=> t('Égypte'),
'AE'=> t('Émirats arabes unis'),
'EC'=> t('Équateur'),
'ER'=> t('Érythrée'),
'US'=> t('États-Unis'),
'ET'=> t('Éthiopie'),
'BV'=> t('Île Bouvet'),
'CX'=> t('Île Christmas'),
'IM'=> t('Île de Man'),
'NF'=> t('Île Norfolk'),
'AX'=> t('Îles Aland'),
'KY'=> t('Îles Caïmans'),
'CC'=> t('Îles Cocos (Keeling)'),
'CK'=> t('Îles Cook'),
'FO'=> t('Îles Féroé'),
'HM'=> t('Îles Heard et MacDonald'),
'FK'=> t('Îles Malouines'),
'MP'=> t('Îles Mariannes du Nord'),
'MH'=> t('Îles Marshall'),
'UM'=> t('Îles mineures éloignées des États-Unis'),
'SB'=> t('Îles Salomon'),
'TC'=> t('Îles Turques-et-Caïques'),
'VI'=> t('Îles Vierges américaines'),
'VG'=> t('Îles Vierges britanniques'),
    ),
    '#default_value' => inpicom_pt_demande_de_devis_get_pays_value($form_state),
  );
  $form['n_et_type_voice'] = array(
    '#type' => 'textfield',
    '#title' => t('N et type de voice'),
    '#default_value' => inpicom_pt_demande_de_devis_get_n_et_type_voice_value($form_state),
  );
  $form['libelle_de_la_voice'] = array(
    '#type' => 'textfield',
    '#title' => t('Libellé de la voice/lieu-dit'),
    '#default_value' => inpicom_pt_demande_de_devis_get_libelle_de_la_voice_value($form_state),
  );
  $form['entree'] = array(
    '#type' => 'textfield',
    '#title' => t('Entreé/Bâtiment'),
    '#default_value' => inpicom_pt_demande_de_devis_get_entree_value($form_state),
  );
  $form['code_postal'] = array(
    '#type' => 'textfield',
    '#title' => t('Code postal'),
    '#maxlength' => 5,
    '#default_value' => inpicom_pt_demande_de_devis_get_code_postal_value($form_state),
  );
  $form['localite'] = array(
    '#type' => 'textfield',
    '#title' => t('Localité'),
    '#maxlength' => 255,
    '#default_value' => inpicom_pt_demande_de_devis_get_localite_value($form_state),
  );
  $form['mention_speciale'] = array(
    '#type' => 'textfield',
    '#title' => t('Mention spéciale'),

    '#default_value' => inpicom_pt_demande_de_devis_get_mention_speciale_value($form_state),
  );
  $form['type_de_telephone'] = array(
    '#type' => 'select',
    '#title' => t('type de téléphone'),
    '#options' => array(
      '' => t('Sélectionner'),
      '483'=> t('Bureau'),
      '480'=> t('Domicile'),
      '486'=> t('Fax'),
      '489'=> t('Mobile'),
    ),
    '#default_value' => inpicom_pt_demande_de_devis_get_type_de_telephone_value($form_state),
  );
  $form['indicatif'] = array(
    '#type' => 'select',
    '#title' => t('Indicatif'),
    '#options' => array(
         ''=> t('Sélectionner'),
'785'=> t('+ 998 (UZ)'),
'692'=> t('+1 (AG)'),
'929'=> t('+1 (BB)'),
'845'=> t('+1 (CA)'),
'752'=> t('+1 (DM)'),
'542'=> t('+1 (DO)'),
'566'=> t('+1 (GD)'),
'710'=> t('+1 (KN)'),
'761'=> t('+1 (LC)'),
'917'=> t('+1 (TT)'),
'899'=> t('+1 (US)'),
'788'=> t('+1 (VC)'),
'635'=> t('+20 (EG)'),
'830'=> t('+212 (MA)'),
'665'=> t('+213 (DZ)'),
'881'=> t('+216 (TN)'),
'905'=> t('+218 (LY)'),
'698'=> t('+220 (GM)'),
'515'=> t('+221 (SN)'),
'521'=> t('+222 (MR)'),
'920'=> t('+223 (ML)'),
'572'=> t('+224 (GN)'),
'908'=> t('+225 (CI)'),
'599'=> t('+226 (BF)'),
'701'=> t('+227 (NE)'),
'857'=> t('+228 (TG)'),
'836'=> t('+229 (BJ)'),
'779'=> t('+231 (LR)'),
'581'=> t('+232 (SL)'),
'791'=> t('+233 (GH)'),
'878'=> t('+234 (NG)'),
'839'=> t('+235 (TD)'),
'605'=> t('+236 (CF)'),
'704'=> t('+237 (CM)'),
'755'=> t('+239 (ST)'),
'821'=> t('+240 (GQ)'),
'854'=> t('+241 (GA)'),
'902'=> t('+242 (CG)'),
'506'=> t('+244 (AO)'),
'866'=> t('+245 (GW)'),
'695'=> t('+248 (SC)'),
'563'=> t('+249 (SD)'),
'722'=> t('+250 (RW)'),
'809'=> t('+254 (KE)'),
'608'=> t('+255 (TZ)'),
'527'=> t('+256 (UG)'),
'860'=> t('+258 (MZ)'),
'617'=> t('+260 (ZM)'),
'656'=> t('+261 (MG)'),
'875'=> t('+263 (ZW)'),
'509'=> t('+264 (NA)'),
'794'=> t('+265 (MW)'),
'596'=> t('+266 (LS)'),
'671'=> t('+267 (BW)'),
'800'=> t('+268 (SZ)'),
'734'=> t('+269 (KM)'),
'518'=> t('+27 (ZA)'),
'764'=> t('+30 (GR)'),
'653'=> t('+31 (NL)'),
'551'=> t('+32 (BE)'),
'638'=> t('+33 (FR)'),
'560'=> t('+34 (ES)'),
'812'=> t('+351 (PT)'),
'818'=> t('+352 (LU)'),
'494'=> t('+353 (IE)'),
'827'=> t('+354 (IS)'),
'575'=> t('+355 (AL)'),
'500'=> t('+356 (MT)'),
'884'=> t('+357 (CY)'),
'536'=> t('+358 (FI)'),
'647'=> t('+359 (BG)'),
'737'=> t('+36 (HU)'),
'623'=> t('+370 (LT)'),
'863'=> t('+371 (LV)'),
'728'=> t('+372 (EE)'),
'545'=> t('+373 (MD)'),
'626'=> t('+374 (AM)'),
'620'=> t('+375 (BY)'),
'539'=> t('+377 (MC)'),
'716'=> t('+378 (SM)'),
'554'=> t('+380 (UA)'),
'782'=> t('+381 (RS)'),
'650'=> t('+382 (ME)'),
'896'=> t('+385 (HR)'),
'725'=> t('+386 (SI)'),
'770'=> t('+387 (BA)'),
'740'=> t('+389 (MK)'),
'503'=> t('+39 (IT)'),
'557'=> t('+40 (RO)'),
'797'=> t('+41 (CH)'),
'731'=> t('+420 (CZ)'),
'548'=> t('+421 (SK)'),
'887'=> t('+423 (LI)'),
'629'=> t('+43 (AT)'),
'632'=> t('+44 (GB)'),
'524'=> t('+45 (DK)'),
'641'=> t('+46 (SE)'),
'677'=> t('+47 (NO)'),
'602'=> t('+48 (PL)'),
'680'=> t('+49 (DE)'),
'851'=> t('+501 (BZ)'),
'926'=> t('+502 (GT)'),
'662'=> t('+503 (SV)'),
'719'=> t('+504 (HN)'),
'668'=> t('+505 (NI)'),
'689'=> t('+506 (CR)'),
'584'=> t('+507 (PA)'),
'773'=> t('+51 (PE)'),
'683'=> t('+52 (MX)'),
'848'=> t('+53 (CU)'),
'869'=> t('+55 (BR)'),
'578'=> t('+56 (CL)'),
'491'=> t('+57 (CO)'),
'872'=> t('+593 (EC)'),
'890'=> t('+60 (MY)'),
'686'=> t('+61 (AU)'),
'614'=> t('+62 (ID)'),
'803'=> t('+63 (PH)'),
'743'=> t('+64 (NZ)'),
'512'=> t('+65 (SG)'),
'842'=> t('+66 (TH)'),
'815'=> t('+673 (BN)'),
'824'=> t('+675 (PG)'),
'569'=> t('+7 (KZ)'),
'590'=> t('+7 (RU)'),
'533'=> t('+81 (JP)'),
'923'=> t('+82 (KR)'),
'914'=> t('+84 (VN)'),
'911'=> t('+850 (KP)'),
'893'=> t('+856 (LA)'),
'674'=> t('+86 (CN)'),
'611'=> t('+90 (TR)'),
'644'=> t('+91 (IN)'),
'497'=> t('+94 (LK)'),
'707'=> t('+953 (SY)'),
'746'=> t('+966 (SA)'),
'530'=> t('+968 (OM)'),
'713'=> t('+971 (AE)'),
'767'=> t('+972 (IL)'),
'806'=> t('+973 (BH)'),
'758'=> t('+974 (QA)'),
'749'=> t('+976 (MN)'),
'932'=> t('+98 (IR)'),
'776'=> t('+992 (TJ)'),
'587'=> t('+993 (TM)'),
'593'=> t('+994 (AZ)'),
'833'=> t('+995 (GE)'),
'659'=> t('+996 (KG)'),
    ),
    '#default_value' => inpicom_pt_demande_de_devis_get_indicatif_value($form_state),
  );
  $form['numero'] = array(
    '#type' => 'textfield',
    '#title' => t('Numéro'),
    '#maxlength' => 255,
    '#default_value' => inpicom_pt_demande_de_devis_get_numero_value($form_state),
  );
}

function inpicom_pt_demande_de_devis_multistep_form_step_four(&$form, &$form_state) {
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('email'),
    '#default_value' => inpicom_pt_demande_de_devis_get_email_value($form_state),
  );
}

function inpicom_pt_demande_de_devis_get_votre_demande_value($form_state) {
  $default_votre_demande_value = '';
  if (isset($form_state['values']['votre_demande'])) {
    $default_votre_demande_value = $form_state['values']['votre_demande'];
  }
  elseif (isset($form_state['storage']['votre_demande'])) {
    $default_votre_demande_value = $form_state['storage']['votre_demande'];
  }
  return $default_votre_demande_value;
}

function inpicom_pt_demande_de_devis_get_civilite_value($form_state) {
  $default_civilite_value = 0;
  if (isset($form_state['values']['civilite'])) {
    $default_civilite_value = $form_state['values']['civilite'];
  }
  elseif (isset($form_state['storage']['civilite'])) {
    $default_civilite_value = $form_state['storage']['civilite'];
  }
  return $default_civilite_value;
}

function inpicom_pt_demande_de_devis_get_nom_value($form_state) {
  $default_nom_value = '';
  if (isset($form_state['values']['nom'])) {
    $default_nom_value = $form_state['values']['nom'];
  }
  elseif (isset($form_state['storage']['nom'])) {
    $default_nom_value = $form_state['storage']['nom'];
  }
  return $default_nom_value;
}

function inpicom_pt_demande_de_devis_get_prenom_value($form_state) {
  $default_prenom_value = '';
  if (isset($form_state['values']['prenom'])) {
    $default_prenom_value = $form_state['values']['prenom'];
  }
  elseif (isset($form_state['storage']['prenom'])) {
    $default_prenom_value = $form_state['storage']['prenom'];
  }
  return $default_prenom_value;
}

function inpicom_pt_demande_de_devis_get_mel_value($form_state) {
  $default_mel_value = '';
  if (isset($form_state['values']['mel'])) {
    $default_mel_value = $form_state['values']['mel'];
  }
  elseif (isset($form_state['storage']['civilite'])) {
    $default_mel_value = $form_state['storage']['mel'];
  }
  return $default_mel_value;
}

function inpicom_pt_demande_de_devis_get_vous_etes_value($form_state) {
  $default_vous_etes_value = 0;
  if (isset($form_state['values']['vous_etes'])) {
    $default_vous_etes_value = $form_state['values']['vous_etes'];
  }
  elseif (isset($form_state['storage']['vous_etes'])) {
    $default_vous_etes_value = $form_state['storage']['vous_etes'];
  }
  return $default_vous_etes_value;
}

function inpicom_pt_demande_de_devis_get_profession_value($form_state) {
  $default_profession_value = '';
  if (isset($form_state['values']['profession'])) {
    $default_profession_value = $form_state['values']['profession'];
  }
  elseif (isset($form_state['storage']['profession'])) {
    $default_profession_value = $form_state['storage']['profession'];
  }
  return $default_profession_value;
}

function inpicom_pt_demande_de_devis_get_role_value($form_state) {
  $default_role_value = 0;
  if (isset($form_state['values']['role'])) {
    $default_role_value = $form_state['values']['role'];
  }
  elseif (isset($form_state['storage']['role'])) {
    $default_role_value = $form_state['storage']['role'];
  }
  return $default_role_value;
}

function inpicom_pt_demande_de_devis_get_pays_value($form_state) {
  $default_pays_value = 0;
  if (isset($form_state['values']['pays'])) {
    $default_pays_value = $form_state['values']['pays'];
  }
  elseif (isset($form_state['storage']['pays'])) {
    $default_pays_value = $form_state['storage']['pays'];
  }
  return $default_pays_value;
}

function inpicom_pt_demande_de_devis_get_n_et_type_voice_value($form_state) {
  $default_n_et_type_voice_value = '';
  if (isset($form_state['values']['n_et_type_voice'])) {
    $default_n_et_type_voice_value = $form_state['values']['n_et_type_voice'];
  }
  elseif (isset($form_state['storage']['n_et_type_voice'])) {
    $default_n_et_type_voice_value = $form_state['storage']['n_et_type_voice'];
  }
  return $default_n_et_type_voice_value;
}

function inpicom_pt_demande_de_devis_get_libelle_de_la_voice_value($form_state) {
  $default_libelle_de_la_voice_value = '';
  if (isset($form_state['values']['libelle_de_la_voice'])) {
    $default_libelle_de_la_voice_value = $form_state['values']['libelle_de_la_voice'];
  }
  elseif (isset($form_state['storage']['libelle_de_la_voice'])) {
    $default_libelle_de_la_voice_value = $form_state['storage']['libelle_de_la_voice'];
  }
  return $default_libelle_de_la_voice_value;
}

function inpicom_pt_demande_de_devis_get_entree_value($form_state) {
  $default_entree_value = '';
  if (isset($form_state['values']['entree'])) {
    $default_entree_value = $form_state['values']['entree'];
  }
  elseif (isset($form_state['storage']['entree'])) {
    $default_entree_value = $form_state['storage']['entree'];
  }
  return $default_entree_value;
}

function inpicom_pt_demande_de_devis_get_code_postal_value($form_state) {
  $default_code_postal_value = '';
  if (isset($form_state['values']['code_postal'])) {
    $default_code_postal_value = $form_state['values']['code_postal'];
  }
  elseif (isset($form_state['storage']['code_postal'])) {
    $default_code_postal_value = $form_state['storage']['code_postal'];
  }
  return $default_code_postal_value;
}

function inpicom_pt_demande_de_devis_get_localite_value($form_state) {
  $default_localite_value = '';
  if (isset($form_state['values']['localite'])) {
    $default_localite_value = $form_state['values']['localite'];
  }
  elseif (isset($form_state['storage']['localite'])) {
    $default_localite_value = $form_state['storage']['localite'];
  }
  return $default_localite_value;
}

function inpicom_pt_demande_de_devis_get_mention_speciale_value($form_state) {
  $default_mention_speciale_value = '';
  if (isset($form_state['values']['mention_speciale'])) {
    $default_mention_speciale_value = $form_state['values']['mention_speciale'];
  }
  elseif (isset($form_state['storage']['mention_speciale'])) {
    $default_mention_speciale_value = $form_state['storage']['mention_speciale'];
  }
  return $default_mention_speciale_value;
}

function inpicom_pt_demande_de_devis_get_type_de_telephone_value($form_state) {
  $default_type_de_telephone_value = 0;
  if (isset($form_state['values']['type_de_telephone'])) {
    $default_type_de_telephone_value = $form_state['values']['type_de_telephone'];
  }
  elseif (isset($form_state['storage']['type_de_telephone'])) {
    $default_type_de_telephone_value = $form_state['storage']['type_de_telephone'];
  }
  return $default_type_de_telephone_value;
}

function inpicom_pt_demande_de_devis_get_indicatif_value($form_state) {
  $default_indicatif_value = 0;
  if (isset($form_state['values']['indicatif'])) {
    $default_indicatif_value = $form_state['values']['indicatif'];
  }
  elseif (isset($form_state['storage']['indicatif'])) {
    $default_indicatif_value = $form_state['storage']['indicatif'];
  }
  return $default_indicatif_value;
}

function inpicom_pt_demande_de_devis_get_numero_value($form_state) {
  $default_numero_value = '';
  if (isset($form_state['values']['numero'])) {
    $default_numero_value = $form_state['values']['numero'];
  }
  elseif (isset($form_state['storage']['numero'])) {
    $default_numero_value = $form_state['storage']['numero'];
  }
  return $default_numero_value;
}

function inpicom_pt_demande_de_devis_get_email_value($form_state) {
  $default_email_value = '';
  if (isset($form_state['values']['email'])) {
    $default_email_value = $form_state['values']['email'];
  }
  elseif (isset($form_state['storage']['email'])) {
    $default_email_value = $form_state['storage']['email'];
  }
  return $default_email_value;
}

function inpicom_pt_demande_de_devis_multistep_form_validate($form, &$form_state) {
  switch ($form_state['step']) {
    case "1":
      break;
    case "2":
    $file = file_save_upload('file_upload', array(
    //'file_validate_is_image' => array(),
    'file_validate_extensions' => array('png gif jpg jpeg'),
    'file_validate_size' => array(1024*1024*2),
  ));
   if ($file) {
    if ($file = file_move($file, 'public://')) {
      $form_state['values']['file_upload'] = $file;
    }
    else {
      form_set_error('file_upload', t('Failed to write the uploaded file the site\'s file folder.'));
    }
  }
  else {
    form_set_error('file_upload', t('No file was uploaded.'));
  }
      break;
    case "3":
      // Check that the third value is alphanumeric
      // if (!preg_match('/^[a-zA-Z]+$/', $form_state['values']['nom'])) {
      //   form_set_error('step_3', t('Alphanumeric characters only please'));
      // }

      break;
  }
}

function inpicom_pt_demande_de_devis_multistep_form_back_submit($form, &$form_state) {
  $form_state['step'] --;
  $form_state['rebuild'] = TRUE;
}

function inpicom_pt_demande_de_devis_multistep_form_submit($form, &$form_state) {
  $step = $form_state['step'];
  inpicom_pt_demande_de_devis_storage_form_value_by_step($step, $form_state);
  if (isset($form_state['values']['forward']) && $form_state['values']['op'] == $form_state['values']['forward']) {
    $form_state['step'] ++;
  }
  elseif (isset($form_state['values']['submit']) && $form_state['values']['op'] == $form_state['values']['submit']) {
    $items = array($form_state['storage']);
    drupal_set_message(t('You submitted the following values:!values', array('!values' => theme('item_list', array('items' => $items)))));
    $form_state['step'] = 1;
    $form_state['storage'] = array();
  }
  $form_state['rebuild'] = TRUE;
}

function inpicom_pt_demande_de_devis_storage_form_value_by_step($step, &$form_state) {
  switch ($step) {
    case 1:
      break;
    case 2:
      inpicom_pt_demande_de_devis_storage_form_value_by_step_two($form_state);
      break;
    case 3:
      inpicom_pt_demande_de_devis_storage_form_value_by_step_three($form_state);
      break;
    case 4:
      $form_state['storage']['email'] = $form_state['values']['email'];
      break;
    default :
      break;
  }
}

function inpicom_pt_demande_de_devis_storage_form_value_by_step_two(&$form_state) {
  $form_state['storage']['votre_demande'] = $form_state['values']['votre_demande'];
  $form_state['storage']['file_upload']   = $form_state['values']['file_upload'];
  $file = $form_state['values']['file_upload'];
  unset($form_state['values']['file_upload']);
  $file->status = FILE_STATUS_PERMANENT;
  file_save($file); 
}

function inpicom_pt_demande_de_devis_storage_form_value_by_step_three(&$form_state) {
  $form_state['storage']['civilite']            = $form_state['values']['civilite'];
  $form_state['storage']['nom']                 = $form_state['values']['nom'];
  $form_state['storage']['prenom']              = $form_state['values']['prenom'];
  $form_state['storage']['mel']                 = $form_state['values']['mel'];
  $form_state['storage']['vous_etes']           = $form_state['values']['vous_etes'];
  $form_state['storage']['profession']          = $form_state['values']['profession'];
  $form_state['storage']['role']                = $form_state['values']['role'];
  $form_state['storage']['pays']                = $form_state['values']['pays'];
  $form_state['storage']['n_et_type_voice']     = $form_state['values']['n_et_type_voice'];
  $form_state['storage']['libelle_de_la_voice'] = $form_state['values']['libelle_de_la_voice'];
  $form_state['storage']['entree']              = $form_state['values']['entree'];
  $form_state['storage']['code_postal']         = $form_state['values']['code_postal'];
  $form_state['storage']['localite']            = $form_state['values']['localite'];
  $form_state['storage']['mention_speciale']    = $form_state['values']['mention_speciale'];
  $form_state['storage']['type_de_telephone']   = $form_state['values']['type_de_telephone'];
  $form_state['storage']['indicatif']           = $form_state['values']['indicatif'];
  $form_state['storage']['numero']              = $form_state['values']['numero'];
}

function inpicom_pt_demande_de_devis_multistep_form_ajax_callback($form, &$form_state) {
  return $form;
}
